[general]

plugin_path = "plugins"
plugins = ["firstplugin"]

protocol_path = "protocols"
protocols = []

[database]
engine = "leveldb" # valid values are 'leveldb' or 'mongodb'

leveldb_path = "onedb"
