[general]
default_prefix = ","
default_nickname = "OneBot"

plugin_path = "plugins"
plugins = ["firstplugin"]

protocol_path = "protocols"
protocols = ["firstprotocol"]

[database]
engine = "leveldb" # valid values are 'leveldb' or 'mongodb'

leveldb_path = "onedb"
