[general]
default_prefix = ","
default_nickname = "OneBot"
# path to default avatar
default_avatar = ""

plugin_path = "plugins"
plugins = ["parrot", "roll", "8ball", "tarkovbud", "money", "comics", "bashquotes"]

protocol_path = "protocols"
protocols = ["matrix", "discord"]

[database]
engine = "leveldb" # valid values are 'leveldb' or 'mongodb'

leveldb_path = "onedb"

[matrix]
# for example: https://matrix.org
home_server = ""
# if using auth_token, it must be in "@username:homeserver" format
auth_user = ""
# if blank, falls back onto auth_pass
auth_token = ""
# if set, this will be used to retrieve an auth token, then the password can be omitted from this file
auth_pass = ""

[discord]
# is set as "Bot auth_token"
auth_token = ""

[irc_bnetd]
# the username of the account on the PvPGN server to login as
nick = ""
# password for above username
pass = ""
# bnetd instance with ircd enabled
server = "localhost:6667"
# channels to autojoin after connection (comma separated)
auto_join = "#Diablo_II-1"

[bnetdbridge]
# bnetd irc channel to watch
channel = "#Diablo_II-1"
# json array of rooms to bridge with bnetd
dest = '[{"protocol":"matrix","channel":"!example:matrix.org"}]'
