name: Build and Publish Release
on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run make build
        run: make rel

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Release notes for version ${{ github.ref }}
          draft: true
          prerelease: false
          artifacts: "onebot-linux.tar.xz"
